<?php

module_load_include('inc', 'bibdk_openuserstatus', 'includes/bibdk_openuserstatus.form');

/**
 * Impelements user_profile_tabs (
 * @see ding_user.module)
 * */
function bibdk_openuserstatus_user_profile2_tabs() {
  $ret = new stdClass();
  $ret->label = t('my_loanerstatus', array(), array('context' => 'bibdk_openuserstatus'));
  $ret->form = 'bibdk_openuserstatus_form';
  $ret->type = 'bibdk_openuserstatus';
  return $ret;
}

/**
 * Implements hook_menu().
 * @return array
 */
function bibdk_openuserstatus_menu() {
  $items = array();
  $items['user/loanerstatus'] = array(
    'title' => t('Loanerstatus'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bibdk_openuserstatus_form'),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_theme().
 * @return array
 */
function bibdk_openuserstatus_theme() {
  return array(
    'bibdk_openuserstatus' => array(
      'variables' => array(
        'loans' => '',
        'loans_count' => '',
        'ready_for_pickup' => '',
        'reservations' => '',
        'fiscal_account' => '',
      ),
      'template' => 'theme/bibdk_openuserstatus',
    ),
  );
}

/**
 * Implement hook_ctools_plugin_api().
 */
function bibdk_openuserstatus_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * do a request
 * @return bool|string | UserStatusResponse
 */
function bibdk_openuserstatus_request() {
  $params = bibdk_openuserstatus_get_params();
  $client = new ting_client_class();
  // this is the real request
  $response = $client->do_userstatusrequest($params);
  if ($response) {
    $response = new UserStatusResponse($response);
  }
  return $response;
}

function bibdk_openuserstatus_get_params() {
  $params = array();
  $params['action'] = 'getUserStatusRequest';
  $params['userId'] = '0413392648';
  $params['userPincode'] = '1234';
  $params['agencyId'] = 'DK-737600';
  $params['outputType'] = 'json';
  return $params;
}