<?php

function openuserstatus_webservice_mockup_menu() {
  $items['openuserstatus_webservice_mockup/renew'] = array(
    'page callback' => 'openuserstatus_webservice_mockup_renew',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Loads the saved renew_loanes_response.jsonm, decodes it and returns.
 * Used for testing only.
 *
 * @return array
 */
function openuserstatus_webservice_mockup_renew() {
  debug('openuserstatus_webservice_mockup_renew');
  $response = drupal_json_decode(file_get_contents(drupal_get_path('module', 'bibdk_openuserstatus') . '/test/mockup/renew_loanes_response.json'));
  debug($response);
  return $response;
}